### ISSUE TITLE
Callbacks to sync on serviceworker state changes.

### ISSUE THREAD

**Issue by chandanbn** [xdrr/cve.js#5]
When state changes are triggered from one browser tab, there should be a way to get callbacks from service worker so other tabs can sync up. These could be login/logout/timeout events.

**Comment by xdrr** [comment]
Because the SW is centralised, all tabs will see the same view on outbound requests. Are you describing a need similar to push notifications? Specifically to notify other tabs when a user has been logged out / timed out?

**Comment by chandanbn** [comment]
yes when a logout event occurs, all open tabs should clear state and show the password prompt.
