### ISSUE TITLE
Bug fixes and new API calls in Vulnogram repo

### ISSUE THREAD

**Issue by chandanbn** [xdrr/cve.js#6]
The current cve.js and cve5sw.js code in Vulnogram has some bug fixes and doesn't nest returned data as {data}. Can you please sync?

**Comment by xdrr** [comment]
Please check the latest changes in CVE.js. The client methods should now be in sync with the API spec in [cveserivces](https://github.com/cveproject/cve-services) and the returned objects have been made consistent (as with errors). If there are still changes you'd like to see let me know.

**Comment by xdrr** [comment]
Closed with https://github.com/Vulnogram/Vulnogram/pull/92
